.gitlab-ci.yml, README.md, build.sh, include/libKitsunePersistence/database/sqlite.h, src/database/sqlite.cpp, src/src.pro, tests/libKitsunePersistence/database/sqlite_test.cpp, tests/libKitsunePersistence/database/sqlite_test.h, tests/main.cpp, tests/tests.pro
=> Add sqlite support

README.md, include/libKitsunePersistence/files/binary_file.h, include/libKitsunePersistence/logger/logger.h, src/files/binary_file.cpp, src/logger/logger.cpp, src/src.pro, tests/libKitsunePersistence/logger/logger_test.cpp, tests/libKitsunePersistence/logger/logger_test.h, tests/main.cpp, tests/tests.pro
=> Add logger

tests/libKitsunePersistence/files/binary_file_test.cpp, tests/libKitsunePersistence/files/binary_file_test.h
added missing tests for the method updateFileSize of the BinaryFile-class.
close #9
=> add missing test

README.md, include/libKitsunePersistence/files/binary_file.h, src/files/binary_file.cpp, tests/libKitsunePersistence/files/binary_file_test.cpp
=> Unbind buffer from binary file

include/libKitsunePersistence/files/binary_file.h, src/files/binary_file.cpp, tests/libKitsunePersistence/files/binary_file_with_directIO_test.cpp, tests/libKitsunePersistence/files/binary_file_with_directIO_test.h, tests/libKitsunePersistence/files/binary_file_without_directIO_test.cpp, tests/libKitsunePersistence/files/binary_file_without_directIO_test.h, tests/main.cpp, tests/tests.pro
=> Make direct io optional

build.sh, include/libKitsunemimiPersistence/files/file_methods.h, src/files/file_methods.cpp, src/files/text_file.cpp, src/src.pro, tests/libKitsunemimiPersistence/files/file_methods_test.cpp, tests/libKitsunemimiPersistence/files/file_methods_test.h, tests/main.cpp, tests/tests.pro
- add file-methods
- new unit-tests
=> Add file methods

CHANGELOG, README.md, src/src.pro
updated for tagging 0.6.1
- unit-tests
=> changes for tag 0.6.1

include/libKitsunemimiPersistence/files/file_methods.h, src/files/file_methods.cpp, tests/libKitsunemimiPersistence/files/file_methods_test.cpp, tests/libKitsunemimiPersistence/files/file_methods_test.h
add new file-methods
- unit-tests
=> Update file methods

build.sh, include/libKitsunemimiPersistence/database/sqlite.h, include/libKitsunemimiPersistence/files/binary_file.h, include/libKitsunemimiPersistence/files/file_methods.h, src/database/sqlite.cpp, src/files/binary_file.cpp, src/files/file_methods.cpp, src/files/text_file.cpp, tests/libKitsunemimiPersistence/database/sqlite_test.cpp, tests/libKitsunemimiPersistence/database/sqlite_test.h, tests/libKitsunemimiPersistence/files/binary_file_with_directIO_test.cpp, tests/libKitsunemimiPersistence/files/binary_file_with_directIO_test.h, tests/libKitsunemimiPersistence/files/binary_file_without_directIO_test.cpp, tests/libKitsunemimiPersistence/files/binary_file_without_directIO_test.h, tests/libKitsunemimiPersistence/files/file_methods_test.cpp, tests/libKitsunemimiPersistence/files/file_methods_test.h, tests/libKitsunemimiPersistence/files/text_file_test.cpp, tests/libKitsunemimiPersistence/files/text_file_test.h, tests/libKitsunemimiPersistence/logger/logger_test.cpp, tests/libKitsunemimiPersistence/logger/logger_test.h
update file-methods and update for using libKitsunemimiCommon 0.10.0
- unit-tests
=> More updates

include/libKitsunemimiPersistence/files/text_file.h, src/files/text_file.cpp, tests/libKitsunemimiPersistence/files/text_file_test.cpp, tests/libKitsunemimiPersistence/logger/logger_test.cpp
Update text file api
- unit-tests
=> Update text file api

CHANGELOG, README.md, src/files/text_file.cpp, src/src.pro
=> updates for tagging 0.7.0

.gitlab-ci.yml, build.sh, src/logger/logger.cpp, src/src.pro, tests/main_with_sqlite.cpp, tests/tests.pro
made sqlite optional
- close #45 
- unit-tests
=> made sqlite optional

src/files/file_methods.cpp, src/files/text_file.cpp
Fix missing check when writing files
- close #37 
- unit-tests
=> Fix missing check when writing files

include/libKitsunemimiPersistence/logger/logger.h, src/logger/logger.cpp, tests/libKitsunemimiPersistence/logger/logger_test.cpp
update initializing of the logger
- unit-tests
=> update initializing of the logger

CHANGELOG, README.md, src/src.pro
updates for tagging 0.8.0
- unit-tests
=> updates for tagging 0.8.0

CHANGELOG, src/src.pro
updates for tagging 0.8.1
- unit-tests
=> updates for tagging 0.8.1

include/libKitsunemimiPersistence/logger/logger.h, src/logger/logger.cpp
- add new setter to update debug-flag
=> add new setter to update debug-flag

include/libKitsunemimiPersistence/files/binary_file.h, src/files/binary_file.cpp, src/files/file_methods.cpp, tests/unit_tests/libKitsunemimiPersistence/files/binary_file_with_directIO_test.cpp, tests/unit_tests/libKitsunemimiPersistence/files/binary_file_with_directIO_test.h, tests/unit_tests/libKitsunemimiPersistence/files/binary_file_without_directIO_test.cpp, tests/unit_tests/libKitsunemimiPersistence/files/binary_file_without_directIO_test.h
- Read complete binary files into buffer
- (not tested)
=> Read complete binary files into buffer

src/files/file_methods.cpp, src/logger/logger.cpp, tests/unit_tests/libKitsunemimiPersistence/logger/logger_test.cpp, tests/unit_tests/unit_tests.pro
- make error, warning and debug output colored
- add console output to unit-tests and checked manually
=> make error, warning and debug output colored

CHANGELOG, README.md, build.sh, src/src.pro
=> changes for tagging 0.9.0

.gitlab-ci.yml, build.sh, libKitsunemimiPersistence.pro
=> made unit-tests optional

include/libKitsunemimiPersistence/logger/logger.h, src/logger/logger.cpp
=> Update colors of logger

CHANGELOG, src/src.pro
=> changes for tagging 0.9.1

include/libKitsunemimiPersistence/database/sqlite.h, src/database/sqlite.cpp, tests/unit_tests/libKitsunemimiPersistence/database/sqlite_test.cpp
- update methods to interact with the sqlite-db
- unit-tests
=> update methods to interact with the sqlite-db

include/libKitsunemimiPersistence/logger/logger.h, tests/unit_tests/libKitsunemimiPersistence/logger/logger_test.cpp
add pink as color for SakuraTree
=> add pink as color for SakuraTree

CHANGELOG, README.md, build.sh, src/src.pro
updates for tagging 0.10.1
- #70 
- ci-pipeline
=> updates for tagging 0.10.1
